# Generated by Django 3.2.6 on 2021-08-21 10:55

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id_ext', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Идентификатор из archilogic')),
                ('title', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Наименование помещения')),
                ('description', models.CharField(blank=True, default=None, max_length=1024, null=True, verbose_name='Описание')),
                ('usage', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Назначение помещения')),
                ('price_per_metr', models.FloatField(blank=True, default=0, null=True, verbose_name='Плата за квадратный метр')),
                ('rent', models.IntegerField(blank=True, default=None, null=True, verbose_name='Признак срока сдачи')),
                ('per_hour', models.FloatField(blank=True, default=0, null=True, verbose_name='Плата за час')),
                ('full_name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='имя арендатора')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта арендатора')),
                ('booked', models.BooleanField(blank=True, default=False, null=True, verbose_name='Забронирован')),
            ],
            options={
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
