# Generated by Django 3.2.6 on 2021-08-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='Почта арендатора'),
        ),
        migrations.AlterField(
            model_name='space',
            name='full_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Имя арендатора'),
        ),
    ]
