# Generated by Django 3.2.6 on 2021-08-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210821_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='id_ext',
            field=models.CharField(max_length=255, verbose_name='Идентификатор из archilogic'),
        ),
    ]
