# Generated by Django 3.2.6 on 2021-08-21 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210821_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='space',
            old_name='id_ext',
            new_name='idExt',
        ),
    ]
