# Generated by Django 3.2.6 on 2021-08-21 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_id_ext_space_idext'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='endRent',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Завершение аренды'),
        ),
        migrations.AddField(
            model_name='space',
            name='startRent',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Начало аренды'),
        ),
    ]
