version: "3.3"

services:
  claster_nginx:
    container_name: nginx
    build:
      context: nginx
    restart: always
    volumes:
      - ../media:/app/media
      - ../static:/app/static
    ports:
      - "80:80"
#      - "443:443"
    links:
      - plx_web

  claster_db:
    container_name: db
    image: postgres:12.0-alpine
    restart: always
    volumes:
      - plx_postgres_data:/var/lib/postgresql/data/
    env_file:
      - $HOME/api/DOCKER_BUILD/.api.env.prod.db

  claster_web:
    container_name: web
    build:
      context: ..
      dockerfile: Dockerfile.prod
    restart: always
    volumes:
      - ../media:/app/media
      - ../static:/app/static
    expose:
      - 8000
    env_file:
      - $HOME/api/DOCKER_BUILD/.api.env.prod
    command: gunicorn claster_api.wsgi:application --bind 0.0.0.0:8000 --workers=3 --threads=2 --worker-class=gthread
    depends_on:
      - claster_db

volumes:
  claster_postgres_data:
