version: "3.7"

services:

  cluster_db:
    container_name: cluster-db
    image: postgres:12.0-alpine
    volumes:
      - postgres_data_api:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=claster_api
      - POSTGRES_USER=claster_api
      - POSTGRES_PASSWORD=claster_passwd

volumes:
  postgres_data_api: