version: "3.7"

services:

  claster_db:
    container_name: api-db
    image: postgres:12.0-alpine
    volumes:
      - postgres_data_api:/var/lib/postgresql/data/
    ports:
      - 15432:5432
    environment:
      - POSTGRES_DB=claster_api
      - POSTGRES_USER=claster_api
      - POSTGRES_PASSWORD=claster_passwd

volumes:
  postgres_data_api: